main:
  "crontab: 0 * * * *":
    - name: service_check_hourly
      imports: https://cnb.cool/dongfg/envs/-/blob/main/github.yml
      stages:
        - name: Service Check Hourly
          script: bash ./checkshell/servicecheck.sh
        - name: Commit and push changes
          script: bash ./checkshell/cnb-commit.sh
  web_trigger_check:
    - name: service_check_manually
      imports: https://cnb.cool/dongfg/envs/-/blob/main/github.yml
      stages:
        - name: Service Check Manually
          script: bash ./checkshell/servicecheck.sh
        - name: Commit and push changes
          script: bash ./checkshell/cnb-commit.sh
