debug: true
endpoints:
  - name: 主站
    url: "https://dongfg.com"
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>dongfg' blog</title>*)"
      - "[RESPONSE_TIME] < 5000"

  - name: Wiki
    enabled: true
    url: "https://wiki.dongfg.com"
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>dongfg' wiki</title>*)"

  - name: 记账服务
    enabled: true
    url: "https://fragile.api.dongfg.com"
    conditions:
      - "[STATUS] == 200"
      - "has([BODY].build) == true"

  - name: Family Site
    enabled: true
    url: "https://drfamily.site"
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>DR.Family*)"
      - "[RESPONSE_TIME] < 5000"

  - name: Serverless Doc
    enabled: true
    url: "https://func.dongfg.com"
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>Serverless Funtions</title>*)"
      - "[RESPONSE_TIME] < 5000"

  - name: VaultWarden 版本
    enabled: true
    url: "https://version.func.dongfg.com/github?repo=dani-garcia/vaultwarden"
    version: 1.28.1
    conditions:
      - "[VERSION] ~1.28.1"
      - "[VERSION] ^1.28.1"