name: Service Status Check

on:
  # schedule:
  #   - cron: "1,25,55 * * * *"

  # 添加手动触发事件
  workflow_dispatch:

jobs:
  service-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Check Service Status
    env:
      WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 新任务挂起
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: page

      - name: Run Shell Script
        id: shell_script_run
        run: |
          chmod +x ./checkshell/servicecheck.sh
          bash ./checkshell/servicecheck.sh

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add -A --force ./logs/
          git commit -m '🆙 [Automated] Update service status logs'
          git push origin page
